name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Read the event JSON
          COMMITS=$(jq -r '.commits[] | "- \(.message) by \(.author.name)"' < $GITHUB_EVENT_PATH)

          # Build message
          BRANCH="${GITHUB_REF##*/}"
          MESSAGE="Git push on branch **$BRANCH**\nCommits:\n$COMMITS"

          # Escape quotes for JSON
          MESSAGE_JSON=$(jq -Rn --arg msg "$MESSAGE" '{"content": $msg}')

          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$MESSAGE_JSON" \
               $WEBHOOK_URL
