name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Read commits from event JSON
          COMMITS=$(jq -r '.commits[] | "- \(.message) by \(.author.name)"' < $GITHUB_EVENT_PATH)

          # Branch name
          BRANCH="${GITHUB_REF##*/}"

          # Build message with actual newlines
          MESSAGE="Git push on branch **$BRANCH**"$'\n'"Commits:"$'\n'"$COMMITS"

          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               $WEBHOOK_URL
