name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Build commit messages
          MESSAGE="Git push on branch **${GITHUB_REF##*/}**\nCommits:"
          for commit in $(jq -r '.commits[].message' <<< "$GITHUB_EVENT_PATH"); do
            MESSAGE="$MESSAGE\n- $commit"
          done

          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               $WEBHOOK_URL
